FROM 11-alpine3.17
LABEL writer="me"
LABEL director="Iam"
RUN wget https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
EXPOSE 80
CMD ["java", "-jar", "/spring-petclinic-2.4.2.jar"]